### ISSUE TITLE
Roc doesn't work on non-44100 ALSA cards

### ISSUE THREAD

**Issue by baranovmv** [roc-project/roc#61] opened 2016-05-14 19:55 UTC
Also sound depends on pulseaudio presence in system. The sounds quality restores only if one plays with pulseaudio
Bad:

```
roc-recv :12345 -vv -t alsa --resampling=no
```

Good:

```
 roc-recv :12345 -vv -t pulseaudio --resampling=no
```

**Comment by gavv** [comment] 2016-05-15 08:58
Actually two bugs here:
* slow playback with ALSA when pulseaudio is *not* installed (this bug);
* silence with ALSA when pulseaudio *is* installed (#62).

**Comment by gavv** [comment] 2016-05-15 09:02
Related to #9.

**Comment by gavv** [comment] 2017-03-26 18:30
The problem is that RPI has 48k card, and we try to play 44100 on it.

What should we do:

* ensure that we can successfully play 44100 without our own resampling on a software ALSA device that performs resampling for us
* ensure that we automatically employ the SoX resampler if the ALSA device doesn't support resampling

To employ SoX resampler, we need to use SoX effect chain. Currently, we use it in `sndio::Reader`, but not in `sndio::Writer`.

**Comment by gavv** [comment] 2017-09-19 06:11
This will be fixed by #85.

**Comment by gavv** [comment] 2017-12-07 06:22
Should be fixed now, needs testing.

**Comment by gavv** [comment] 2019-01-03 13:18
### Testing

If rate is not set, roc-recv autodetects 48k:

```
$ ./roc-recv -vv -s :10001 -r :10002 -t alsa --latency 50000 --resampler-window=32
...
[debug] roc_sndio: [sox] alsa.c: select_format: trying #7
[info] roc_sndio: [sox] alsa.c: selecting format 7: S32_LE (Signed 32 bit Little Endian)
[info] roc_sndio: sox writer: bits=32 out_rate=48000 in_rate=0 ch=2 is_file=0
...
```

If the user explicitly requests 48k, it works too:

```
$ ./roc-recv -vv -s :10001 -r :10002 -t alsa --latency 100000 --resampler-window=32 --rate 48000
...
[debug] roc_sndio: [sox] alsa.c: select_format: trying #7
[info] roc_sndio: [sox] alsa.c: selecting format 7: S32_LE (Signed 32 bit Little Endian)
[info] roc_sndio: sox writer: bits=32 out_rate=48000 in_rate=48000 ch=2 is_file=0
...
```

During playback, we also ensure that roc-recv really uses 48k:

```
$ cat /proc/asound/card2/pcm0p/sub0/hw_params 
access: MMAP_INTERLEAVED
format: S16_LE
subformat: STD
channels: 2
rate: 48000 (48000/1)
period_size: 1024
buffer_size: 16384
```

If the user explicitly requests another rate, it doesn't work:

```
$ ./roc-recv -vv -s :10001 -r :10002 -t alsa --latency 10000 --resampler-window=32 --rate=44100
...
[debug] roc_sndio: [sox] alsa.c: select_format: trying #7
[info] roc_sndio: [sox] alsa.c: selecting format 7: S32_LE (Signed 32 bit Little Endian)
[info] roc_sndio: [sox] formats.c: can't set sample rate 44100; using 48000
[error] roc_sndio: sox writer: can't open output file or device with the required sample rate: required=48000 suggested=44100
[error] roc_recv: can't open output file or device: (null) alsa
[debug] roc_sndio: sox writer: closing output
```

If the user explicitly disables resampling, it doesn't work because the network rate (44100) and the sound card rate (48k) differ:

```
$ ./roc-recv -vv -s :10001 -r :10002 -t alsa --latency 10000 --resampler-window=32 --no-resampling
...
[debug] roc_sndio: [sox] alsa.c: select_format: trying #7
[info] roc_sndio: [sox] alsa.c: selecting format 7: S32_LE (Signed 32 bit Little Endian)
[info] roc_sndio: [sox] formats.c: can't set sample rate 44100; using 48000
[error] roc_sndio: sox writer: can't open output file or device with the required sample rate: required=48000 suggested=44100
[error] roc_recv: can't open output file or device: (null) alsa
[debug] roc_sndio: sox writer: closing output
```

**Closed** 2019-01-03 13:19 UTC
Labels: bug
