### ISSUE TITLE
Print total latency in -vv mode

### ISSUE THREAD

**Issue by baranovmv** [roc-project/roc#66] opened 2016-05-15 12:16 UTC
It's useful to know how much time Roc needs to play received samples.

**Comment by baranovmv** [comment] 2016-05-15 12:31
1. Compute the packets queue length (in samples) beside `Streamer` in the moment when datagrams queue has minimal length;
2. Add size of `Resampler::curr_frame_` — it must be equal `Resampler::frame_size_`
3. Add the length of the samples queue behind the resampler and before the renderers thread.

**Comment by gavv** [comment] 2017-03-27 09:04
SHould be covered by #78.

**Comment by gavv** [comment] 2017-12-07 05:39
1. We have this.
2. We don't have this yet.
3. There is no additional output latency between anymore.
4. However, SoX/PulseAudio has its own latency too.
5. We probably also want to take RTT into account.

**Comment by gavv** [comment] 2019-05-30 17:48
Closing as a duplicate of #127.

**Closed by gavv** 2019-05-30 17:48 UTC
Labels: enhancement
