### ISSUE TITLE
roc_audio panics on OS X

### ISSUE THREAD

**Issue by dshil** [roc-project/roc#106] opened 2017-08-29 02:34 UTC
Again, after rebasing on latest resampler changes I've surprisingly got. Maybe @baranovmv shouldn't be blamed in this case :)

```
[debug] roc_netio: parse address: parsed 127.0.0.1:12345
[debug] roc_audio: sample buffer queue: max_size=100
[debug] roc_netio: udp receiver: attaching to event loop
[debug] roc_netio: udp sender: attaching to event loop
[info] roc_netio: udp receiver: adding port 127.0.0.1:12345
[debug] roc_netio: udp receiver: opening port 127.0.0.1:12345
[debug] roc_sndio: writer: opening: name=(null) type=(null)
[info] roc_sndio: initializing sox
[debug] roc_sndio: driver waveaudio is not supported
[debug] roc_sndio: selecting default driver coreaudio
[debug] roc_sndio: detected defaults: name=default type=coreaudio
[info] roc_sndio: writer: name=default type=coreaudio
[info] roc_netio: transceiver: starting event loop
[debug] roc_sndio: writer: starting thread
[info] roc_pipeline: receiver: starting thread: output_latency=6400 session_latency=8640
[debug] roc_audio: delayed writer: starting output: latency=6400 pending=6400
[info] roc_pipeline: session manager: creating session 127.0.0.1:64178
[debug] roc_fec: of block decoder: initializing Reed-Solomon decoder
[debug] roc_audio: resampler: initializing window
[debug] roc_audio: resampler: initializing window
[info] roc_packet: packet router: auto-detected route for new packet: route=0
[debug] roc_pipeline: session: attaching readers to sink
[info] roc_packet: packet router: auto-detected route for new packet: route=1
[info] roc_audio: delayer: received enough packets: delay=8640 samples=9600 packets=30
[info] roc_fec: fec decoder: got marker bit, start decoding: n_packets_before=0 blk_sn=12414
[debug] roc_audio: streamer: got first packet: ch=0 zero_samples=8960
[debug] roc_audio: streamer: got first packet: ch=1 zero_samples=8960
[info] roc_audio: scaler: received enough samples: queue_size=9600 aim_queue_size=8640
[debug] roc_audio: scaler: queue_size=09600 freq_coeff=1.00001
[debug] roc_audio: scaler: queue_size=08960 freq_coeff=1.00069

src/modules/roc_audio/resampler.cpp:216: error: roc_panic() called

PANIC: roc_audio: x > (window_len_ << FRACT_BIT_COUNT)

Traceback (most recent call last):
# 14  libsystem_pthread.dylib             0x00007fff917bb3ed thread_start + 13
# 13  libsystem_pthread.dylib             0x00007fff917bdfd7 _pthread_body + 0
# 12  libsystem_pthread.dylib             0x00007fff917be05a _pthread_body + 131
# 11  roc-recv                            0x000000010130915d uv__thread_start + 61
# 10  roc-recv                            0x00000001012c8584 _ZN3roc4core6Thread14thread_runner_EPv + 36
# 9   roc-recv                            0x00000001012d46ba _ZN3roc8pipeline8Receiver3runEv + 122
# 8   roc-recv                            0x00000001012d48e9 _ZN3roc8pipeline8Receiver4tickEv + 441
# 7   roc-recv                            0x00000001012bf6ff _ZN3roc5audio12ChannelMuxer4readERKNS_4core11BufferSliceIfNS2_7IBufferIfEENS2_15RefCntOwnershipEEE + 47
# 6   roc-recv                            0x00000001012c6c15 _ZN3roc5audio6Zipper4readERKNS_4core11BufferSliceIfNS2_7IBufferIfEENS2_15RefCntOwnershipEEE + 421
# 5   roc-recv                            0x00000001012c0bd6 _ZN3roc5audio5Mixer4readERKNS_4core11BufferSliceIfNS2_7IBufferIfEENS2_15RefCntOwnershipEEE + 278
# 4   roc-recv                            0x00000001012c2541 _ZN3roc5audio9Resampler4readERKNS_4core11BufferSliceIfNS2_7IBufferIfEENS2_15RefCntOwnershipEEE + 401
# 3   roc-recv                            0x00000001012c2f56 _ZN3roc5audio9Resampler9resample_Em + 1494
# 2   roc-recv                            0x00000001012c3411 _ZN3roc5audio9Resampler5sinc_Ejf + 97
# 1   roc-recv                            0x00000001012c80c5 _ZN3roc4core8do_panicEPKcS2_iS2_z + 581
# 0   roc-recv                            0x00000001012c770e _ZN3roc4core15print_backtraceEv + 142
[1]    4370 abort      ./bin/x86_64-pc-apple-darwin14.5.0/roc-recv -vv 127.0.0.1:12345
```

**Comment by gavv** [comment] 2017-09-19 06:26
Well, it seems that this is not specific to OS X. Closing this as a duplicate of #84.

**Closed by gavv** 2017-09-19 06:26 UTC
Labels: bug
