### ISSUE TITLE
Configurable Resampler

### ISSUE THREAD

**Issue by baranovmv** [roc-project/roc#84] opened 2017-06-13 15:27 UTC
Resampler uses fixed size window and constant FIR-filter. If it'll use configurable window length, that will let us performance and sound quality.

Resampler should get these parameters from config:
* window length, enum [32, 64, 128, 256], 64 by default;
* window sub-integer points number, enum [64, 128, 256], 64 by default.

In order to make tunable window length, resampler should build sinc_table with variable length on its own during construction.
Should it use malloc for that?

**Comment by baranovmv** [comment] 2017-07-05 21:20
It's turned out that upsampling introduces high-frequency aliases outside the main band.
E.g. upsampling twice a sinewave with frequency of Pi/4 (8 samples per period) gives us this artefacts on spectrum:
![upscale_2](https://user-images.githubusercontent.com/1952503/27884446-15333802-61dd-11e7-8dfa-5f8ce40906a6.png)
The blue curve is a spectrum of the original sinewave and the red one is the result of the resampling algorithm.
The second harmonic of the genuine sinewave on -150 dB is due to limited precision of 32-bit floating point. I've checked that by switching the whole code-base to double precision: the second harmonic has disappeared and noise floor has been gone down.

I suppose that the reason of the high-frequency aliases belongs to the limited length of the FIR filter inside the resampler. I have some bases for that belief, which I'm going to unfold in a featured article.

Though, it doesn't concern downsampling and that side of the band must be filtered out by a sound-card during digital-analog conversion.

**Comment by baranovmv** [comment] 2017-08-25 17:20
Resampler accepts few more parameters now:
* `window_len` -- the length of the sinc FIR; is in branch "resampler";
* `frame_size` -- number of samples in Resampler's internal frame, must be greater than window_len***max(freq_coeff)**; is in branch "resampler";
* `channels` -- number of interleaved channels in input buffers; is available in branch "multichannel_resampler"

**Comment by baranovmv** [comment] 2017-08-25 17:25
Resamplers isn't aware of maximum `freq_coeff`, so it checks the condition with *roc_panic* every time the scaling factor is being set.
@gavv Is there any place we know maximum possible `freq_coeff`?

**Comment by gavv** [comment] 2017-09-19 06:02
For now, a panic is possible:

```
src/modules/roc_audio/resampler.cpp:216: error: roc_panic() called

PANIC: roc_audio: x > (window_len_ << FRACT_BIT_COUNT)
```

Full log: https://gist.github.com/gavv/6512f88671ef640cc6a3f6ec06c3ad9b

Probably, I broke ResamplerUpdater in latest refactoring.

**Comment by gavv** [comment] 2017-09-19 06:22
It seems that the bug was introduced after the latest resampler updater, but before my refactoring, see #106.

**Comment by gavv** [comment] 2017-09-19 07:46
You can reproduce it by transmitting a long file, like 10 or 15 minutes.

**Comment by gavv** [comment] 2017-09-20 05:30
If I simply remove the check:

```
roc_panic_if(x > (window_len_ << FRACT_BIT_COUNT));
```

everything works fine. Note that sinc_table_ is core::Array, which have bounds checking in operator[], so there are no out of bounds reads or writes.

**Comment by gavv** [comment] 2017-09-20 06:03
583e9d3f76894f3a2663b4d0182281a89b676735

**Comment by gavv** [comment] 2019-01-04 19:24
It seems that the check is just incorrect.

The check is:

```
roc_panic_if(x > (window_len_ << FRACT_BIT_COUNT));
```

On default config, it expands to the following condition for `x`:

```
x <= 64 << 20
x <= 64 * 2^20
x <= 67108864
```

However the real condition should be:

```
x >> (FRACT_BIT_COUNT - window_interp_bits_) + 1 < window_len_ * window_interp_ + 2
```

Which expands to:

```
x >> (20 - 9) < 64 * 512 + 2
x >> 11 < 32770
x / 2^11 < 32770
x < 67112960
```

And thus allows slightly bigger values for `x`.

Since the real boundary checking didn't report any errors either (when it was enabled), I'm removing this check and closing this issue for now.

**Closed by gavv** 2019-01-04 19:24 UTC
Labels: enhancement, performance
